version: '3.3'
services:
  satis-server:
    ports:
      - '9100:80'
    volumes:
      - ./data/satis:/etc/satis
      - ./data/satis-server:/etc/satis-server
    container_name: satis_server
    image: 'satis-server-dev:latest'
    environment:
      DEBUG_MODE_ENABLED: true
      BEARER_UPSTREAM_ENDPOINT: 'https://idp.example.com/api/auth/profile'
    build:
      context: ../.
      dockerfile: Dockerfile
